### ISSUE TITLE
Feature: User can record their workout details

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can record details about their workout. These details will include the date they completed the workout, how long the workout took, the amount of calories burnt, the muscle groups worked, and any additional details that the user wants to include.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will have a form in front of them. There will be a date input box for the date section, a text input for the workout duration, calories burned, and details section, and a button to add different muscle groups. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/132747186-47a1390e-a973-4817-b19b-dbf14e667fd1.png)

![image](https://user-images.githubusercontent.com/85311223/132747136-1ba1af68-c6fa-4341-9d93-b2e91bfa4236.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create database and name it
- [x] Update `schema.sql` to DB Designer schema
- [x] Create tables for the database
- [x] Add muscle names and id for db
- [x] Add dummy data

### ☁️ Server

- [x] install Express 
- [x] Update `server/index.js` to handle post requests to /app/newWorkout
- [x] Set up DB query to appropriately upload data
- [x] Send a DB query and then using the returning id that was generated by the database, implement another row into the muscleworkoutgroup table of my database
- [x] Have error handlers for invalid inputs
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a client folder to house my modules
- [x] Install all necessary packages
- [x] Create a component to record workout details
- [x] Update component to handle submits

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
