### ISSUE TITLE
Feature: User can sign up for an account

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be presented with a sign-up page. If they input a username, password, first name, and a last name, they will be able to sign in with that username and password. The username and password will be saved into the database. The user will be assigned a userId.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/133657511-5fa3841b-4fc7-4881-96a5-e3f6d01bb409.png)
![image](https://user-images.githubusercontent.com/85311223/133657536-99185905-0a87-42a1-9f85-e7049d135e5d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a post route to create a new account
- [x] Server should receive information about a username, first name, last name, and a password
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to handle account creation
- [x] Create a component to input a username, password, first name, and a last name
- [x] Create a component to allow the user to submit
- [x] Create a component to allow the user to go to the sign in page
### 🧑‍⚕️ Clean Up

- [x] #20
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
