### ISSUE TITLE
Feature: User can record their diet details

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can record a meal and its details.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will input data into a form. Once they click on submit, this will send a request to the server to upload the data to the database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/132920666-a7dfb2c3-8464-40ce-abfb-4dd73dcddbd7.png)

![image](https://user-images.githubusercontent.com/85311223/132920636-35699586-3b79-4553-8646-037a92edc3c4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include a notes section for a new meal

### ☁️ Server

- [x] Update `server/index.js` to handle post requests to app/new/meal
- [x] Update server./index.js to handle file uploads as well so that i can save images somewhere
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to so that the user can input information in
- [x] Make sure that there is an option to upload image as well
- [x] Will essentially be very similar to the new workout page
- [x] Implement hash routing

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
