### ISSUE TITLE
Feature: User can sign in

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign into their account. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user inputs their username and password. If these things are valid, they will be taken to the home page which should be the fitness report. If not, then they will be given an error message that prompts them to sign in again.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/133669850-0aedb05a-92e7-49f1-8665-f8743f6c4968.png)

![image](https://user-images.githubusercontent.com/85311223/133669824-b54a0d1d-e8ce-4ba2-9f3f-028016638bdc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle sign in attempts
- [x] The user should receive a token for signing in which they can use to view their own things
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component that is a form to allow the user to sign in
- [x] Update the register component to have a link to take the user to the sign in page
- [x] Once the user clicks on the sign in button and if they are able to successfully sign in, have them be taken to the fitness report page

### 🧑‍⚕️ Clean Up

- [x] Need to refactor files so that it will only use the userId of the person that is currently signed in
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
