### ISSUE TITLE
Feature: User can log out

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#23]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log out

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the hamburger menu on the left, the user can log out of their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/133705157-b9cef4b7-0c6e-4375-8a43-316bcb69caef.png)
![image](https://user-images.githubusercontent.com/85311223/133705160-66a560a5-9a2f-4a4a-8fb3-16edd51955e4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Create a component in the app drawer to log out
- [ ] Logging out should clear the local storage of the token

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
