### ISSUE TITLE
Feature: User can see past workouts

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view past workouts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user will be able to view their past workouts. This feature will also include an app drawer on the side that allows a user to navigate between pages. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/133164460-96dc277c-c2c8-449a-8e76-f1b8b9d66d26.png)

![image](https://user-images.githubusercontent.com/85311223/133164421-f6f433b2-2c97-4ca3-b12a-95cc662fb021.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` if I need to change any of the categories

### ☁️ Server

- [x] Update `server/index.js` to send a get request to my database to retrieve information such as date, length, calories burned, muscle groups, and details
- [x] Update the get request so that the muscle groups that are worked out can be aggregated into the same workout rather than the same workout being sent multiple times but with different muscles worked out for each time
- [x] Make sure that no data is altered
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create an app drawer to show links that I can click on
- [x] Look into cards and grids to have a mobile responsive demonstration
- [x] Have each workout be on a card that can expand to show more details
- [x] Have the app switch pages to the corresponding link that is clicked
- [x] Have the app show the past workouts
- [x] Past workouts need to be shown by order of date posted with the newest one being at the top

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
