### ISSUE TITLE
Feature: User can see past meals

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see past meals

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By going to the 'Your Meals' page, they can see past meals that they uploaded.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/133319629-7fd826e9-c742-4b52-8f82-9eb2cf7b11ce.png)
![image](https://user-images.githubusercontent.com/85311223/133319633-5b0c5817-0863-4ad4-bad1-22352efda539.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get requests for api/your/meals
- [x] Be able to locate the right image in the right location
- [x] Be able to send the right image
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display individual meals in cards like I did with the workouts
- [x] Implement similar cards to the past workouts feature
- [x] Have the cards show a preview of the meal that the user uploaded

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
