### ISSUE TITLE
Feature: User can receive a weekly analysis of their fitness

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see an analysis of their past week of exercise. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

This page will serve as the home page so as soon as the user opens up the app, this will be the front page. It should show things like:
 - How many times did the user workout?
 - How long was the average workout session?
 - Which muscle groups were worked out this past week?
 - Average calories burned
 - Total Calories burned

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/133499789-0743c3ed-0df6-45d8-8fc3-1b90df137152.png)
![image](https://user-images.githubusercontent.com/85311223/133500004-7b58a3bc-af50-499f-93ad-52b937dbe2fc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a get request for workouts but only for the past week
- [x] Since I will be pulling multiple entries, I need to separate various categories of data
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Since I am allowing the user to customize the time, the server needs to be able to receive specific requests

### ⚡ Client

- [x] Create a component to display weekly information
- [x] Create a component to actually allow the user to change which days they want to pull information from, which will change it from a weekly analysis to just a time analysis of their workouts
### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
