### ISSUE TITLE
Feature: User can see other people's workouts

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view other people's workouts.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view other people's workouts by going to the social tab, and then selecting the user that they want to see. When an individual user is clicked, the app will take them to a page where the user's workouts are laid out in cards, much like that of the own user's workouts. They should be able to click on a workout to see details.

This feature is where the user can actually begin to interact with other users. I will first have to implement the account creation system now, as well as a sign in. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/133531940-1efb366c-cccd-4e58-b64f-d6ce77885114.png)

![image](https://user-images.githubusercontent.com/85311223/133531914-fcea4544-c3a6-4a78-9f1d-8c66ce92adb9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle get requests to pull a list of all users except oneself
- [x] Update 'server/index.js' tp handle get requests to pull workouts about an individual user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show a list of other users
- [x] Create components that allow individual users to be selected
- [x] Create a component such that when an individual is selected, their workouts should show up 
- [x] Each workout should be able to be expanded by clicking on them

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
