### ISSUE TITLE
Feature: User can see other people's meals

### ISSUE THREAD

**Issue by dennymin** [dennymin/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85311223/134090974-f7f8f292-a815-4f96-8945-76b1366661fe.png)

![image](https://user-images.githubusercontent.com/85311223/134090877-99202d30-1035-4e7b-910b-7c4df991e641.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to handle get requests with the user id parameter and with the search parameter meals
- [ ] Have the server be able to locate the image that is given to it by the database
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to choose between either fitness or meals
- [ ] Create a component that renders a page of the specified user's meals
- [ ] Create a component to show what the preview photo looks like
- [ ] The client should be able to seamlessly go between the fitness page and the meals page

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
